"""Builds website/ from the last demo run."""
from __future__ import annotations
import pathlib
from . import sitekit as sk

ROOT = pathlib.Path(__file__).resolve().parent.parent
META = {
    "name": "Risk Portfolio Service",
    "slug": "risk-portfolio-saas",
    "repo": "5.0-Ai-Engineering-Toolkit",
    "pillar": "Financial Stability",
    "tagline": "Portfolio in, risk report out — three VaR methods reported side by "
               "side, risk attributed by Euler decomposition, and findings surfaced "
               "without being asked for.",
    "tags": [("JSON in / JSON out", ""), ("3 VaR methods", ""),
             ("Euler attribution", ""), ("synthetic market", "demo")],
    "banner": "The market is synthetic — a factor model with fat tails and a crash "
              "regime, generated by src/demo.py. The service is real and the numbers "
              "are computed, but no market data and no client portfolio is involved.",
}


def build_site(results: dict) -> pathlib.Path:
    reps, val, th = results["reports"], results["validation"], results["throughput"]
    eq = reps["EQUAL-WEIGHT"]

    metrics = sk.metric_grid([
        ("Portfolios scored", len(reps), f"{results['n_tickers']} names each"),
        ("Bad requests rejected",
         f"{sum(c['rejected'] for c in val['cases'])}/{len(val['cases'])}",
         "none let through"),
        ("Throughput", f"{th['requests_per_second']:,.0f}/s",
         f"{th['mean_latency_ms']:.1f} ms per report"),
        ("Observations", results["observations"], "per name"),
    ])

    risk_tbl = sk.table(
        ["Portfolio", "Ann. vol", "VaR historical", "VaR Gaussian",
         "VaR Cornish-Fisher", "Expected shortfall", "Max drawdown"],
        [[pid, f"{r['risk']['annualised_volatility']:.3f}",
          f"{r['risk']['var_historical']:.4f}", f"{r['risk']['var_gaussian']:.4f}",
          f"{r['risk']['var_cornish_fisher']:.4f}",
          f"{r['risk']['expected_shortfall']:.4f}",
          f"{r['risk']['max_drawdown']:.3f}"] for pid, r in reps.items()],
        numeric_cols=(1, 2, 3, 4, 5, 6))

    var_chart = sk.bar_chart(
        [(f"{pid[:11]} · {k}", reps[pid]["risk"][f"var_{k}"])
         for pid in reps for k in ("historical", "gaussian", "cornish_fisher")],
        fmt="{:.4f}")

    contrib_tbl = sk.table(
        ["Ticker", "Capital weight", "Risk share", "Risk / capital"],
        [[c["ticker"], f"{c['weight']:.1%}", f"{c['risk_share']:.1%}",
          f"{c['risk_share'] / c['weight']:.2f}×" if c["weight"] else "—"]
         for c in reps["HIDDEN-RISK"]["contributions"]],
        numeric_cols=(1, 2, 3))

    check_rows = [[pid, c["level"], c["code"], c["detail"]]
                  for pid, r in reps.items() for c in r["checks"]]
    check_tbl = sk.table(["Portfolio", "Level", "Code", "Detail"], check_rows)

    val_tbl = sk.table(
        ["Rejected request", "Caught", "Message returned"],
        [[c["case"], "yes" if c["rejected"] else "NO", c["detail"]]
         for c in val["cases"]])

    body = f"""
<section>
  <h2>Three VaR numbers, because the disagreement is the information</h2>
  <div class="stack">
    <p>A VaR figure without its method attached is not interpretable. Historical,
    Gaussian and Cornish-Fisher VaR disagree on the same portfolio, and how much they
    disagree tells you how far the return distribution is from the one the parametric
    number assumes.</p>
    <p>So the report gives all three and flags the gap. A service that quoted one number
    would be easier to read and would hide the only thing worth knowing about it.</p>
  </div>
</section>

<section>
  <h2>This run</h2>
  <div class="stack-lg">
    {metrics}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      generated {sk.esc(results['generated_at'])} &middot; {sk.esc(results['data_source'])}
    </p>
    {risk_tbl}
    {var_chart}
    <div class="note">
      <h3>Cornish-Fisher was reported below Gaussian until a sign was fixed</h3>
      <p>On a fat left tail the Cornish-Fisher correction must push VaR <em>up</em>. The
      first version applied the expansion to the positive quantile and negated
      afterwards, which flips the sign of the skew term and produced a corrected VaR
      <em>below</em> the uncorrected one — the exact opposite of the correction's
      purpose. The formula looked right; printing the two numbers side by side made it
      obvious in a second.</p>
    </div>
  </div>
</section>

<section>
  <h2>Where the risk actually is</h2>
  <div class="stack-lg">
    {contrib_tbl}
    <div class="note">
      <h3>The last column is the point of the service</h3>
      <p>The HIDDEN-RISK portfolio looks well diversified by capital — eight positions,
      {reps['HIDDEN-RISK']['concentration']['effective_positions']:.1f} effective
      positions, nothing above 18%. By risk it is not: the top position carries
      {reps['HIDDEN-RISK']['contributions'][0]['risk_share'] / reps['HIDDEN-RISK']['contributions'][0]['weight']:.2f}×
      its capital share.</p>
      <p>Contributions come from an Euler decomposition and sum exactly to portfolio
      volatility, which is what makes them an allocation of risk rather than a set of
      scores. A capital-based position limit is structurally unable to see this, which
      is why the ratio is a check rather than a chart.</p>
    </div>
  </div>
</section>

<section>
  <h2>Findings the service raises unprompted</h2>
  <div class="stack-lg">
    {check_tbl}
    <p>A risk system that only answers the question asked is a calculator. These fire on
    every report without being requested.</p>
  </div>
</section>

<section>
  <h2>Rejecting bad input</h2>
  <div class="stack-lg">
    {val_tbl}
    <p>Every rejection names what is wrong and what was received. The alignment check
    matters most: a ticker with no market data is refused rather than dropped, because
    silent misalignment is what makes a risk system dangerous rather than merely wrong
    — the numbers still come out, they just describe a different portfolio.</p>
  </div>
</section>

<section>
  <h2>Reproduce it</h2>
  <div class="stack">
    <pre>cd risk-portfolio-saas
pip install -r requirements.txt
python -m pytest tests/ -q
python -m src.demo</pre>
    <p>The service surface is one function — <code>handle(request, market)</code>, JSON
    in and JSON out — so a FastAPI or Flask layer is a thin adapter rather than a
    rewrite. None is included, because the framework is not the part worth showing.</p>
  </div>
</section>

<section>
  <h2>What this does not establish</h2>
  <div class="stack">
    <ul class="tight">
      <li>Synthetic market data. No real prices, no real portfolio, no client.</li>
      <li>{results['observations']} observations per name. A 95% historical VaR
      estimated from this much data has a wide confidence interval that the report
      does not show.</li>
      <li>Single-period risk only. No liquidity horizon, no margin, no funding, and
      no netting across accounts.</li>
      <li>Stress scenarios are single-factor beta shocks. Real stress testing
      requires correlated multi-factor scenarios and a view on how correlations
      themselves move.</li>
      <li>No persistence, authentication, tenancy or rate limiting — none of the
      things that make a service a service. This is the analytics core only.</li>
    </ul>
  </div>
</section>
"""
    return sk.build(ROOT, META, body, results)
